name: p_hn25
description: "Aplicación médica. MedicalHand"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  get_it: ^7.6.7
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.1
  google_sign_in: ^6.3.0
  lottie: ^3.3.1
  flutter_native_splash: ^2.4.6
  hugeicons: ^0.0.11
  image_picker: ^1.2.0
  connectivity_plus: ^6.1.5
  intl: ^0.20.2
  shimmer: ^3.0.0
  path_provider: ^2.1.5
  path: ^1.9.1
  firebase_storage: ^13.0.1
  firebase_app_check: ^0.4.0+1
  firebase_messaging: ^16.0.1
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^19.4.2
  google_fonts: ^6.3.1
  http: ^1.5.0
  url_launcher: ^6.3.2
  permission_handler: ^12.0.1
  mobile_scanner: ^7.1.2
  dio: ^5.9.0
  open_filex: ^4.7.0
  device_info_plus: ^12.1.0
  image_gallery_saver_plus: ^4.0.1
  flutter_image_compress: ^2.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/
    - assets/animation/

flutter_native_splash:
  color: '#A5D6A7'
  image: assets/images/icono.png
  android: true
  ios: true
  web: false

