// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZUnijXo8PvvZgDVjiXgFXoxH1qEvd0aY',
    appId: '1:818500504209:web:3f14483c96b006accc8d30',
    messagingSenderId: '818500504209',
    projectId: 'medicalhand-f2fd3',
    authDomain: 'medicalhand-f2fd3.firebaseapp.com',
    storageBucket: 'medicalhand-f2fd3.firebasestorage.app',
    measurementId: 'G-RD0F272WGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW1cOuEUXKHXd6qF9Od69v2mZBdxvFZjo',
    appId: '1:818500504209:android:598abc7d1a4075fbcc8d30',
    messagingSenderId: '818500504209',
    projectId: 'medicalhand-f2fd3',
    storageBucket: 'medicalhand-f2fd3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9RL8BTosGSqJmtKI7TRpUx2iwpIlr9iA',
    appId: '1:818500504209:ios:1607bdbd398c3abacc8d30',
    messagingSenderId: '818500504209',
    projectId: 'medicalhand-f2fd3',
    storageBucket: 'medicalhand-f2fd3.firebasestorage.app',
    iosBundleId: 'com.example.pHn25',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9RL8BTosGSqJmtKI7TRpUx2iwpIlr9iA',
    appId: '1:818500504209:ios:1607bdbd398c3abacc8d30',
    messagingSenderId: '818500504209',
    projectId: 'medicalhand-f2fd3',
    storageBucket: 'medicalhand-f2fd3.firebasestorage.app',
    iosBundleId: 'com.example.pHn25',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZUnijXo8PvvZgDVjiXgFXoxH1qEvd0aY',
    appId: '1:818500504209:web:2b180d87a531bf6bcc8d30',
    messagingSenderId: '818500504209',
    projectId: 'medicalhand-f2fd3',
    authDomain: 'medicalhand-f2fd3.firebaseapp.com',
    storageBucket: 'medicalhand-f2fd3.firebasestorage.app',
    measurementId: 'G-EQHQH6KGXM',
  );
}
